/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import Excepciones.PalabraNoEncontrada;
import Excepciones.ClaveIncorrecta;
import Excepciones.UsuarioNoEncontrado;
import Excepciones.UsuarioRepetido;
import ahorcadoV5.Ahorcadov4;
import static ahorcadoV5.Ahorcadov4.USUARIO_ARCH;
import Entidades.Diccionario;
import Entidades.ListaUsuarios;
import Entidades.Usuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author luloop
 */
public class frmNuevoUsuario extends javax.swing.JDialog
{

    //<editor-fold desc="Atributos">
    private boolean isDialog = false;
    private boolean esNuevo = false;
    private ListaUsuarios todosUsuarios;

    private int accion;

    // </editor-fold>
    //<editor-fold desc="Constructores">
    public frmNuevoUsuario(java.awt.Frame parent, boolean modal, int accion)
    {
        super(parent, modal);
        this.setContentPane(new JLabel(new ImageIcon("fondoUsuario.jpg")));
        initComponents();
        this.accion = accion;
        this.titulo.setIcon(new ImageIcon("nuevousuario-26.png"));
        this.btnCancelar.setIcon(new ImageIcon("botones-15.png"));
        this.btnCancelar.setRolloverIcon(new ImageIcon("botones-16.png"));
        this.btnAceptar.setIcon(new ImageIcon("botones-17.png"));
        this.btnAceptar.setRolloverIcon(new ImageIcon("botones-18.png"));

    }

    // </editor-fold>        
    //<editor-fold desc="Actions">
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        txMail = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        texClave = new javax.swing.JPasswordField();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(488, 354));
        setMinimumSize(new java.awt.Dimension(488, 354));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(488, 354));
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Rockwell Condensed", 0, 48)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText(" ");
        titulo.setMaximumSize(new java.awt.Dimension(400, 70));
        titulo.setMinimumSize(new java.awt.Dimension(400, 70));
        titulo.setPreferredSize(new java.awt.Dimension(400, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Usuario");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Clave");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mail");

        txNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txNombreKeyTyped(evt);
            }
        });

        btnCancelar.setBorder(null);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.setMaximumSize(new java.awt.Dimension(121, 35));
        btnCancelar.setMinimumSize(new java.awt.Dimension(121, 35));
        btnCancelar.setPreferredSize(new java.awt.Dimension(121, 35));
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setBorder(null);
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.setFocusPainted(false);
        btnAceptar.setMaximumSize(new java.awt.Dimension(121, 35));
        btnAceptar.setMinimumSize(new java.awt.Dimension(121, 35));
        btnAceptar.setPreferredSize(new java.awt.Dimension(121, 35));
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });

        texClave.setText("\"                                       \"");
        texClave.setMaximumSize(new java.awt.Dimension(111, 20));
        texClave.setMinimumSize(new java.awt.Dimension(111, 20));
        texClave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                texClaveActionPerformed(evt);
            }
        });
        texClave.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                texClaveKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txNombre)
                        .addComponent(txMail)
                        .addComponent(texClave, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(texClave, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelarActionPerformed
    {//GEN-HEADEREND:event_btnCancelarActionPerformed
        this.setVisible(false);
        this.setIsDialog(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarActionPerformed
    {//GEN-HEADEREND:event_btnAceptarActionPerformed
      guardarTOdo();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        todosUsuarios = ListaUsuarios.cargarUsuarios(ahorcadoV5.Ahorcadov4.USUARIO_ARCH);
        System.out.println(todosUsuarios.toString());
        this.texClave.setText("");
         this.texClave.addFocusListener(new FocusListener()
        {
            @Override
            public void focusGained(FocusEvent e)
            {
                texClave.setText("");
            }

            @Override
            public void focusLost(FocusEvent e)
            {
                // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        
        
         this.texClave.addKeyListener(new KeyListener()
        {
            @Override
            public void keyTyped(KeyEvent e)
            {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyPressed(KeyEvent e)
            {
                if (e.getKeyCode() == KeyEvent.VK_ENTER)
                {
                   guardarTOdo();
                }
            }

            @Override
            public void keyReleased(KeyEvent e)
            {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
         
         
    }//GEN-LAST:event_formWindowOpened

    private void txNombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txNombreKeyTyped
    {//GEN-HEADEREND:event_txNombreKeyTyped

    }//GEN-LAST:event_txNombreKeyTyped

    private void texClaveKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_texClaveKeyReleased
    {//GEN-HEADEREND:event_texClaveKeyReleased
      
    }//GEN-LAST:event_texClaveKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        //  frmLogIn aux = new frmLogIn();// TODO add your handling code here:
        //  aux.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void texClaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_texClaveActionPerformed
    {//GEN-HEADEREND:event_texClaveActionPerformed
        this.texClave.setText("");       
    }//GEN-LAST:event_texClaveActionPerformed

    public static void main(String args[])
    {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmNuevoUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmNuevoUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmNuevoUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmNuevoUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmNuevoUsuario dialog = new frmNuevoUsuario(new javax.swing.JFrame(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
        private void limpiarPassText()
    {
        this.texClave.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField texClave;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txMail;
    private javax.swing.JTextField txNombre;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>  
    //<editor-fold desc="Get-Set">
    public boolean isEsNuevo()
    {
        return esNuevo;
    }

    public void setEsNuevo(boolean esNuevo)
    {
        this.esNuevo = esNuevo;
    }

    public boolean isIsDialog()
    {
        return isDialog;
    }

    public void setIsDialog(boolean isDialog)
    {
        this.isDialog = isDialog;
    }

    //</editor-fold>
    //<editor-fold desc="Metodo">
    /////////////////////////////// ALTA BAJA MODIFICACION
    protected void baja(Usuario listaUsuario) throws UsuarioNoEncontrado, ClaveIncorrecta
    {
        listaUsuario = this.todosUsuarios.validarListaUsuarios(this.txNombre.getText(), this.texClave.getText());
        int i = this.todosUsuarios.getLista().indexOf(listaUsuario);

        if (this.todosUsuarios.baja(listaUsuario, this.txNombre.getText(), this.texClave.getText()))
        {
            JOptionPane.showMessageDialog(this, "Usuario Borrado");
            this.setVisible(false);
        }
    }

    protected boolean alta(boolean flag)
    {
        if (this.todosUsuarios.alta(flag, this.txNombre.getText()))
        {
            flag = true;
        }
        return flag;
    }

    protected void modificacion(Usuario listaUsuario) throws UsuarioNoEncontrado, ClaveIncorrecta
    {
        if (this.todosUsuarios.modificacion(listaUsuario, this.txNombre.getText(), this.texClave.getText(), this.txMail.getText()))
        {
            System.out.println("Mail Modificado");
            JOptionPane.showMessageDialog(this, "Mail Modificado");
            this.setVisible(false);
        }
    }

    /**
     * Limpia Formulario
     */
    protected void limpiarFormulario()
    {
        this.texClave.setText("-----");
        this.txMail.setText("");
        this.txNombre.setText("");
    }

    
    private void guardarTOdo()
    {
         boolean flag = false;
        Usuario listaUsuario = null;

        try
        {
            if (this.txNombre.getText().length() > 0 && this.texClave.getText().length() > 0)
            {
                switch (this.accion)
                {
                    case 0://ALTA  
                        flag = alta(flag);
                        if (flag == false)
                        {
                            if (this.txMail.getText().length() > 0)
                            {
                                this.todosUsuarios.agregar(new Usuario(this.txNombre.getText(), this.texClave.getText(), this.txMail.getText()));
                                JOptionPane.showMessageDialog(this, "Usuario Agregado");

                                if (ListaUsuarios.guardarUsuarios(this.todosUsuarios, ahorcadoV5.Ahorcadov4.USUARIO_ARCH))
                                {
                                    System.out.println("Lista Guardada con Exito");
                                }

                                this.setVisible(false);
                                this.isDialog = true;
                                this.esNuevo = true;

                            }
                            else
                            {
                                JOptionPane.showMessageDialog(this, "FALTA INGRESAR MAIL");
                            }
                        }
                        else
                        {
                            throw new Excepciones.UsuarioRepetido("Usuario Repetido");
                        }

                        break;

                    case 1://BAJA
                        this.baja(listaUsuario);
                        ListaUsuarios.guardarUsuarios(this.todosUsuarios, USUARIO_ARCH);
                        this.setVisible(false);
                        this.isDialog = true;
                        break;

                    case 2://MODIFICACION
                        modificacion(listaUsuario);
                        ListaUsuarios.guardarUsuarios(this.todosUsuarios, USUARIO_ARCH);
                        this.setVisible(false);
                        this.isDialog = true;
                        break;
                }
            }
        }
        catch (UsuarioNoEncontrado | ClaveIncorrecta | UsuarioRepetido ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            limpiarFormulario();
        }
    }
            
    // </editor-fold>
}
